### ISSUE TITLE
RISE - logo

### ISSUE THREAD

**Issue by alajom** [ASU-EnergySystems-Software/RISE#41]
Remove Dr. Johnson's head and get a more professional logo.

**Comment by sjscott9** [comment]
Updated favicon with a blue lightning bolt ("Did You Know..." this is the same lightning bolt shape used in the graph wizard for power)

Commit https://github.com/ASU-EnergySystems-Software/RISE/commit/1f8949da5056094159000ca8073a83f82ec6c645
