### ISSUE TITLE
Fault Zones - Turn Status Off

### ISSUE THREAD

**Issue by alajom** [ASU-EnergySystems-Software/RISE#44]
When a fault area activated, change nodes and connection status from on -> off

**Comment by sjscott9** [comment]
Upon fault activation (i.e., delay expires) the components within the fault zone's status are set to OFF on server side.

Commit https://github.com/ASU-EnergySystems-Software/RISE/commit/23b2c01ae94f24f3fe8a8c5eea79123d2769c8a0
