### ISSUE TITLE
Graphs - Capacitor and Voltage Regulator icons

### ISSUE THREAD

**Issue by alajom** [ASU-EnergySystems-Software/RISE#45]
Add icons to the wizard

**Comment by sjscott9** [comment]
Downsize font, get rid of voltage regulator in wizard

**Comment by sjscott9** [comment]
Capacitor icon was added (it was already there but the SVG/XML needed adjustment), and Synchronous Generator text was changed to 12px from 16px font size to fit inside the column in commit https://github.com/ASU-EnergySystems-Software/RISE/commit/67a3e127d4bfca13be594ef87d19e12cfcb9866b
