### ISSUE TITLE
Graphs - OTHER OUTPUTS

### ISSUE THREAD

**Issue by msmtms** [ASU-EnergySystems-Software/RISE#49]
We need to see other outputs for graphs, 

current_1_magnitude
"" angle
real_power
reactive power
...

**Comment by sjscott9** [comment]
Outputs have been accounted for in the wizard and on the graph, and update in the chart during a calculation.

Commit https://github.com/ASU-EnergySystems-Software/RISE/commit/276fc11368d82c1b5ed59388563c996c87d339f2
